const $=selector=>document.querySelector(selector),config=window.TNKAX_SUPABASE||{};
const configured=config.url&&!config.url.startsWith("YOUR_")&&config.anonKey&&!config.anonKey.startsWith("YOUR_");
const db=configured?window.supabase.createClient(config.url,config.anonKey):null;let data={products:[],categories:[]},categorySortable,productSortable,selectedCategoryId;

async function init(){if(!db){$("#login-error").textContent="Chưa cấu hình Supabase.";return}const{data:{session}}=await db.auth.getSession();if(session)showDashboard(session.user)}
async function showDashboard(user){$("#login").hidden=true;$("#dashboard").hidden=false;$("#admin-email").textContent=user?.email||"admin";await refresh()}
async function refresh(){const[categories,products]=await Promise.all([db.from("categories").select("*").order("sort_order"),db.from("products").select("*,categories(name)").order("created_at",{ascending:false})]);if(categories.error)return alert(categories.error.message);if(products.error)return alert(products.error.message);data.categories=categories.data;data.products=products.data.sort((a,b)=>(a.sort_order||999999)-(b.sort_order||999999)||b.created_at.localeCompare(a.created_at));renderProducts();renderCategories();if(selectedCategoryId)openCategoryProducts(selectedCategoryId);$("#product-count").textContent=data.products.length;$("#category-count").textContent=data.categories.length;$("#view-count").textContent=data.products.reduce((sum,item)=>sum+(item.views||0),0).toLocaleString("vi-VN");$("#product-form select").innerHTML=data.categories.map(item=>`<option value="${item.id}">${item.name}</option>`).join("")}
function renderProducts(){$("#admin-products").innerHTML=data.products.length?data.products.map(item=>`<article class="admin-card"><img src="${item.image_url}" alt=""><small>${item.categories?.name||"Chưa phân loại"}</small>${item.title?`<h3>${item.title}</h3>`:""}<div><button data-edit="${item.id}">Sửa</button><button data-delete="${item.id}">Xóa</button></div></article>`).join(""):'<div class="empty-products"><i>♡</i><h3>Kho mẫu đang trống</h3><p>Bấm “Thêm sản phẩm” để đăng mẫu thiết kế đầu tiên.</p></div>'}
function renderCategories(){$("#admin-categories").innerHTML=data.categories.map((item,index)=>`<div class="category-row ${selectedCategoryId===item.id?"selected":""}" data-category-id="${item.id}"><button class="drag-handle" type="button" aria-label="Kéo để sắp xếp">☷</button><span class="priority-number">${String(index+1).padStart(2,"0")}</span><b>${item.name}</b><button class="manage-products" data-manage-category="${item.id}">Sản phẩm</button><button data-delete-category="${item.id}">Xóa</button></div>`).join("");categorySortable?.destroy();categorySortable=Sortable.create($("#admin-categories"),{animation:180,handle:".drag-handle",ghostClass:"sorting-ghost",chosenClass:"sorting-chosen",onEnd:()=>{$("#save-category-order").hidden=false;updatePriorityNumbers()}})}
function updatePriorityNumbers(){document.querySelectorAll(".category-row .priority-number").forEach((number,index)=>number.textContent=String(index+1).padStart(2,"0"))}
function openCategoryProducts(categoryId){selectedCategoryId=categoryId;const category=data.categories.find(item=>item.id===categoryId),products=data.products.filter(item=>item.category_id===categoryId);$("#category-products-panel").hidden=false;$("#selected-category-name").textContent=category?.name||"Danh mục";$("#sortable-products").innerHTML=products.length?products.map((item,index)=>`<article class="sortable-product" data-product-id="${item.id}"><span>${String(index+1).padStart(2,"0")}</span><img src="${item.image_url}" alt=""><div><b>${item.title||"Không tên"}</b><small>Giữ và kéo để đổi vị trí</small></div><i>☷</i></article>`).join(""):'<div class="no-category-products">Danh mục này chưa có sản phẩm.</div>';productSortable?.destroy();if(products.length)productSortable=Sortable.create($("#sortable-products"),{animation:180,handle:".sortable-product",ghostClass:"sorting-ghost",chosenClass:"sorting-chosen",onEnd:()=>{$("#save-product-order").hidden=false;updateProductNumbers()}});renderCategories()}
function updateProductNumbers(){document.querySelectorAll(".sortable-product>span").forEach((number,index)=>number.textContent=String(index+1).padStart(2,"0"))}

$("#login-form").onsubmit=async event=>{event.preventDefault();$("#login-error").textContent="Đang đăng nhập...";const form=new FormData(event.target),result=await db.auth.signInWithPassword({email:form.get("username"),password:form.get("password")});if(result.error){$("#login-error").textContent="Email hoặc mật khẩu không đúng.";return}$("#login-error").textContent="";showDashboard(result.data.user)};
$("#logout").onclick=async()=>{await db.auth.signOut();location.reload()};
document.querySelectorAll("[data-tab]").forEach(button=>button.onclick=()=>{const products=button.dataset.tab==="products";$("#products-tab").hidden=!products;$("#categories-tab").hidden=products;$("#page-heading").textContent=products?"Kho sản phẩm":"Danh mục";$("#add-product").hidden=!products;document.querySelectorAll("[data-tab]").forEach(item=>item.classList.toggle("active",item===button))});

const dialog=$("#product-dialog"),form=$("#product-form");
$("#add-product").onclick=()=>{form.reset();form.id.value="";form.views.value=0;$("#form-title").textContent="Thêm sản phẩm";dialog.showModal()};
$("#cancel").onclick=$("#cancel-bottom").onclick=()=>dialog.close();
$("#admin-products").onclick=async event=>{const edit=event.target.dataset.edit,remove=event.target.dataset.delete;if(edit){const item=data.products.find(product=>product.id===edit);form.id.value=item.id;form.title.value=item.title;form.category.value=item.category_id;form.description.value=item.description||"";form.image.value=item.image_url;form.views.value=item.views;$("#form-title").textContent="Sửa sản phẩm";dialog.showModal()}if(remove&&confirm("Bạn chắc chắn muốn xóa sản phẩm này?")){const result=await db.from("products").delete().eq("id",remove);if(result.error)return alert(result.error.message);refresh()}};
form.onsubmit=async event=>{event.preventDefault();const submit=form.querySelector('[type="submit"]'),original=submit.textContent;submit.disabled=true;submit.textContent="Đang lưu...";const values=new FormData(form),file=values.get("file");let imageUrl=values.get("image");if(file?.size){const extension=file.name.split(".").pop(),path=`${Date.now()}-${crypto.randomUUID()}.${extension}`;const upload=await db.storage.from("product-images").upload(path,file);if(upload.error){submit.disabled=false;submit.textContent=original;return alert(upload.error.message)}imageUrl=db.storage.from("product-images").getPublicUrl(path).data.publicUrl}if(!imageUrl){submit.disabled=false;submit.textContent=original;return alert("Vui lòng chọn ảnh hoặc nhập URL ảnh.")}const categoryId=values.get("category"),payload={title:values.get("title").trim(),category_id:categoryId,description:values.get("description"),image_url:imageUrl,views:Number(values.get("views"))||0},id=values.get("id");const result=id?await db.from("products").update(payload).eq("id",id):await db.from("products").insert(payload);submit.disabled=false;submit.textContent=original;if(result.error)return alert(result.error.message);dialog.close();refresh()};
$("#category-form").onsubmit=async event=>{event.preventDefault();const result=await db.from("categories").insert({name:new FormData(event.target).get("name"),sort_order:data.categories.length});if(result.error)return alert(result.error.message);event.target.reset();refresh()};
$("#save-category-order").onclick=async()=>{const button=$("#save-category-order"),rows=[...document.querySelectorAll(".category-row")];button.disabled=true;button.textContent="Đang lưu...";const results=await Promise.all(rows.map((row,index)=>db.from("categories").update({sort_order:index+1}).eq("id",row.dataset.categoryId)));const error=results.find(result=>result.error)?.error;button.disabled=false;if(error){button.textContent="Thử lưu lại";return alert(error.message)}button.textContent="✓ Đã lưu";setTimeout(()=>{button.hidden=true;button.textContent="✓ Lưu thứ tự"},1000);await refresh()};
$("#admin-categories").onclick=async event=>{const manage=event.target.dataset.manageCategory,id=event.target.dataset.deleteCategory;if(manage){openCategoryProducts(manage);return}if(id&&confirm("Xóa danh mục này?")){const result=await db.from("categories").delete().eq("id",id);if(result.error)return alert("Hãy xóa hoặc chuyển sản phẩm trong danh mục trước.");if(selectedCategoryId===id){selectedCategoryId=null;$("#category-products-panel").hidden=true}refresh()}};
$("#save-product-order").onclick=async()=>{const button=$("#save-product-order"),rows=[...document.querySelectorAll(".sortable-product")];button.disabled=true;button.textContent="Đang lưu...";const results=await Promise.all(rows.map((row,index)=>db.from("products").update({sort_order:index+1}).eq("id",row.dataset.productId)));const error=results.find(result=>result.error)?.error;button.disabled=false;if(error){button.textContent="Thử lưu lại";return alert(error.message.includes("sort_order")?"Bạn cần chạy file supabase/add-product-order.sql trong SQL Editor trước.":error.message)}button.textContent="✓ Đã lưu";setTimeout(()=>{button.hidden=true;button.textContent="✓ Lưu thứ tự sản phẩm"},1000);await refresh()};init();
