const state={products:[],categories:[],active:"Tất cả"};
const sections=document.querySelector("#category-sections"),filters=document.querySelector("#filters"),empty=document.querySelector("#empty");
const escapeHtml=value=>String(value??"").replace(/[&<>"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]));
const config=window.TNKAX_SUPABASE||{};
const configured=config.url&&!config.url.startsWith("YOUR_")&&config.anonKey&&!config.anonKey.startsWith("YOUR_");
const db=configured?window.supabase.createClient(config.url,config.anonKey):null;
async function load(){if(!db){sections.innerHTML='<div class="empty">Website chưa được kết nối Supabase. Hãy cập nhật <code>supabase-config.js</code>.</div>';return}try{const[categoryResult,productResult]=await Promise.all([db.from("categories").select("id,name,sort_order").order("sort_order"),db.from("products").select("id,title,category_id,description,image_url,views,created_at,categories(name)").order("created_at",{ascending:false})]);if(categoryResult.error)throw categoryResult.error;if(productResult.error)throw productResult.error;state.categories=categoryResult.data;state.products=productResult.data.map(item=>({id:item.id,title:item.title,category:item.categories?.name||"Khác",description:item.description,image:item.image_url,views:item.views||0,createdAt:item.created_at}));render()}catch(error){sections.innerHTML=`<div class="empty">${escapeHtml(error.message)}</div>`}}
function render(){renderFilters();renderSections()}function renderFilters(){filters.innerHTML=["Tất cả",...state.categories.map(item=>item.name)].map(name=>`<button class="${state.active===name?"active":""}" data-category="${escapeHtml(name)}">${escapeHtml(name)}</button>`).join("")}function card(item){return `<article class="product-card"><button class="thumb" data-id="${item.id}"><img src="${escapeHtml(item.image)}" alt="${escapeHtml(item.title)}" loading="lazy"></button><div class="product-meta"><span>◉ ${Number(item.views).toLocaleString("vi-VN")}</span><b>${escapeHtml(item.title)}</b></div></article>`}
function renderSections(){const names=state.active==="Tất cả"?state.categories.map(item=>item.name):[state.active];sections.innerHTML="";let total=0;names.forEach((name,index)=>{const items=state.products.filter(item=>item.category===name);if(!items.length)return;total+=items.length;const section=document.createElement("section");section.className="category-block";section.dataset.expanded="false";section.innerHTML=`<div class="category-ribbon"><span>${String(index+1).padStart(2,"0")}</span><h3>${escapeHtml(name)}</h3><i>♡</i></div><div class="products-grid">${items.map((item,i)=>`<div class="product-slot ${i>=8?"extra":""}">${card(item)}</div>`).join("")}</div>${items.length>8?'<button class="section-toggle">Xem tất cả <span>＋</span></button>':""}`;sections.appendChild(section)});empty.hidden=total>0}
filters.addEventListener("click",event=>{const button=event.target.closest("[data-category]");if(!button)return;state.active=button.dataset.category;render();document.querySelector("#portfolio").scrollIntoView({behavior:"smooth"})});document.querySelectorAll("[data-jump]").forEach(link=>link.addEventListener("click",()=>{state.active=link.dataset.jump;render()}));
sections.addEventListener("click",event=>{const toggle=event.target.closest(".section-toggle");if(toggle){const section=toggle.closest(".category-block"),expanded=section.dataset.expanded==="true";section.dataset.expanded=String(!expanded);toggle.innerHTML=expanded?'Xem tất cả <span>＋</span>':'Thu gọn <span>−</span>';if(expanded)section.scrollIntoView({behavior:"smooth",block:"start"});return}const button=event.target.closest("[data-id]");if(!button)return;const item=state.products.find(product=>product.id===button.dataset.id);if(!item)return;document.querySelector("#modal-image").src=item.image;document.querySelector("#modal-title").textContent=item.title;document.querySelector("#modal-category").textContent=item.category;document.querySelector("#modal-description").textContent=item.description||"Liên hệ để đặt thiết kế theo phong cách mẫu này.";document.querySelector("#modal").classList.add("open");document.body.classList.add("locked");db.rpc("increment_product_views",{product_id:item.id}).then(()=>{})});document.addEventListener("click",event=>{if(event.target.closest("[data-close]")){document.querySelector("#modal").classList.remove("open");document.body.classList.remove("locked")}});document.addEventListener("keydown",event=>{if(event.key==="Escape"){document.querySelector("#modal").classList.remove("open");document.body.classList.remove("locked")}});load();
